
import { Transaction } from "src/lib/models/transactions";

export const transactions: Transaction[] = [
    // --- Starting with your existing transactions ---
    {
        id: "0",
        userId: "0",
        date: new Date("2025-11-29"),
        description: "Walmart Supercentre",
        amount: 60.71,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "1",
        userId: "0",
        date: new Date("2025-11-28"),
        description: "Shawarma Palace",
        amount: 12.71,
        institution: "VISA",
        tag: "restaurant",
    },

    // --- Newly Generated Transactions (Approx. 98 more) ---

    // Major Monthly Expenses (Checking/Transfer)
    {
        id: "2",
        userId: "0",
        date: new Date("2025-11-01"),
        description: "Monthly Rent Payment",
        amount: 1850.00,
        institution: "Checking",
        tag: "rent",
    },
    {
        id: "3",
        userId: "0",
        date: new Date("2025-11-04"),
        description: "Auto Insurance Premium",
        amount: 165.50,
        institution: "Checking",
        tag: "insurance",
    },
    {
        id: "4",
        userId: "0",
        date: new Date("2025-11-07"),
        description: "Hydro/Electricity Bill",
        amount: 98.45,
        institution: "Checking",
        tag: "utilities",
    },
    {
        id: "5",
        userId: "0",
        date: new Date("2025-11-07"),
        description: "Internet & TV Service",
        amount: 125.00,
        institution: "Checking",
        tag: "utilities",
    },
    {
        id: "6",
        userId: "0",
        date: new Date("2025-11-10"),
        description: "Student Loan Payment",
        amount: 350.00,
        institution: "Checking",
        tag: "debt",
    },
    {
        id: "7",
        userId: "0",
        date: new Date("2025-11-15"),
        description: "Cell Phone Bill",
        amount: 75.00,
        institution: "Checking",
        tag: "utilities",
    },
    {
        id: "8",
        userId: "0",
        date: new Date("2025-11-20"),
        description: "Gas Utility Bill",
        amount: 42.10,
        institution: "Checking",
        tag: "utilities",
    },
    {
        id: "9",
        userId: "0",
        date: new Date("2025-11-25"),
        description: "Renter's Insurance",
        amount: 18.99,
        institution: "Checking",
        tag: "insurance",
    },

    // Vehicle/Gas Expenses (VISA/Checking)
    {
        id: "10",
        userId: "0",
        date: new Date("2025-11-02"),
        description: "Esso Gas Station",
        amount: 55.25,
        institution: "VISA",
        tag: "gas",
    },
    {
        id: "11",
        userId: "0",
        date: new Date("2025-11-09"),
        description: "Shell Gas Station",
        amount: 60.15,
        institution: "VISA",
        tag: "gas",
    },
    {
        id: "12",
        userId: "0",
        date: new Date("2025-11-16"),
        description: "Oil Change Service",
        amount: 79.99,
        institution: "VISA",
        tag: "auto_maintenance",
    },
    {
        id: "13",
        userId: "0",
        date: new Date("2025-11-21"),
        description: "Petro-Canada",
        amount: 58.70,
        institution: "VISA",
        tag: "gas",
    },
    {
        id: "14",
        userId: "0",
        date: new Date("2025-11-26"),
        description: "Car Wash Token",
        amount: 12.00,
        institution: "VISA",
        tag: "auto_maintenance",
    },

    // Groceries and Food
    {
        id: "15",
        userId: "0",
        date: new Date("2025-11-03"),
        description: "No Frills Groceries",
        amount: 45.88,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "16",
        userId: "0",
        date: new Date("2025-11-05"),
        description: "Coffee Shop - Morning Latte",
        amount: 4.50,
        institution: "VISA",
        tag: "coffee",
    },
    {
        id: "17",
        userId: "0",
        date: new Date("2025-11-06"),
        description: "Local Pizzeria",
        amount: 28.50,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "18",
        userId: "0",
        date: new Date("2025-11-08"),
        description: "Costco Bulk Buy",
        amount: 185.32,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "19",
        userId: "0",
        date: new Date("2025-11-10"),
        description: "Tim Hortons",
        amount: 6.85,
        institution: "VISA",
        tag: "coffee",
    },
    {
        id: "20",
        userId: "0",
        date: new Date("2025-11-11"),
        description: "Lunch Sandwich Shop",
        amount: 15.25,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "21",
        userId: "0",
        date: new Date("2025-11-13"),
        description: "Food Basics",
        amount: 32.19,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "22",
        userId: "0",
        date: new Date("2025-11-14"),
        description: "Starbucks",
        amount: 5.10,
        institution: "VISA",
        tag: "coffee",
    },
    {
        id: "23",
        userId: "0",
        date: new Date("2025-11-15"),
        description: "Dinner at Thai Place",
        amount: 55.00,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "24",
        userId: "0",
        date: new Date("2025-11-17"),
        description: "Loblaws Groceries",
        amount: 78.41,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "25",
        userId: "0",
        date: new Date("2025-11-19"),
        description: "Uber Eats Delivery",
        amount: 38.90,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "26",
        userId: "0",
        date: new Date("2025-11-20"),
        description: "Bulk Barn Baking Supplies",
        amount: 18.55,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "27",
        userId: "0",
        date: new Date("2025-11-22"),
        description: "Weekend Brunch",
        amount: 42.00,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "28",
        userId: "0",
        date: new Date("2025-11-24"),
        description: "Sobeys Express",
        amount: 22.10,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "29",
        userId: "0",
        date: new Date("2025-11-27"),
        description: "McDonald's Drive Thru",
        amount: 9.60,
        institution: "VISA",
        tag: "restaurant",
    },

    // Entertainment & Subscriptions
    {
        id: "30",
        userId: "0",
        date: new Date("2025-11-01"),
        description: "Netflix Subscription",
        amount: 16.99,
        institution: "VISA",
        tag: "subscription",
    },
    {
        id: "31",
        userId: "0",
        date: new Date("2025-11-05"),
        description: "Spotify Premium",
        amount: 10.99,
        institution: "VISA",
        tag: "subscription",
    },
    {
        id: "32",
        userId: "0",
        date: new Date("2025-11-12"),
        description: "Movie Tickets",
        amount: 28.00,
        institution: "VISA",
        tag: "entertainment",
    },
    {
        id: "33",
        userId: "0",
        date: new Date("2025-11-18"),
        description: "Video Game Purchase (Online)",
        amount: 79.99,
        institution: "VISA",
        tag: "entertainment",
    },

    // Shopping & Misc.
    {
        id: "34",
        userId: "0",
        date: new Date("2025-11-04"),
        description: "Amazon Order - Toiletries",
        amount: 45.60,
        institution: "VISA",
        tag: "shopping",
    },
    {
        id: "35",
        userId: "0",
        date: new Date("2025-11-10"),
        description: "Local Hardware Store - Tools",
        amount: 112.50,
        institution: "VISA",
        tag: "home_maintenance",
    },
    {
        id: "36",
        userId: "0",
        date: new Date("2025-11-23"),
        description: "Clothes Shopping - Jacket",
        amount: 95.00,
        institution: "VISA",
        tag: "shopping",
    },
    {
        id: "37",
        userId: "0",
        date: new Date("2025-11-29"),
        description: "Black Friday Electronics",
        amount: 350.00,
        institution: "VISA",
        tag: "shopping",
    },
    {
        id: "38",
        userId: "0",
        date: new Date("2025-11-30"),
        description: "Donation to Charity",
        amount: 25.00,
        institution: "Checking",
        tag: "charity",
    },

    // --- More Groceries, Restaurants, Gas, and Coffee for volume ---
    {
        id: "39",
        userId: "0",
        date: new Date("2025-11-01"),
        description: "Local Deli",
        amount: 18.20,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "40",
        userId: "0",
        date: new Date("2025-11-02"),
        description: "Fresh Market Produce",
        amount: 33.75,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "41",
        userId: "0",
        date: new Date("2025-11-03"),
        description: "Starbucks Refill",
        amount: 4.80,
        institution: "VISA",
        tag: "coffee",
    },
    {
        id: "42",
        userId: "0",
        date: new Date("2025-11-04"),
        description: "Pizza Hut",
        amount: 22.99,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "43",
        userId: "0",
        date: new Date("2025-11-05"),
        description: "Pioneer Gas Station",
        amount: 48.50,
        institution: "VISA",
        tag: "gas",
    },
    {
        id: "44",
        userId: "0",
        date: new Date("2025-11-06"),
        description: "Shoppers Drug Mart",
        amount: 15.45,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "45",
        userId: "0",
        date: new Date("2025-11-07"),
        description: "Pub Night Drinks",
        amount: 35.00,
        institution: "VISA",
        tag: "entertainment",
    },
    {
        id: "46",
        userId: "0",
        date: new Date("2025-11-08"),
        description: "Subway Lunch",
        amount: 11.50,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "47",
        userId: "0",
        date: new Date("2025-11-09"),
        description: "Home Depot Supplies",
        amount: 55.70,
        institution: "VISA",
        tag: "home_maintenance",
    },
    {
        id: "48",
        userId: "0",
        date: new Date("2025-11-10"),
        description: "T&T Supermarket",
        amount: 68.30,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "49",
        userId: "0",
        date: new Date("2025-11-11"),
        description: "Quick Stop Coffee",
        amount: 3.50,
        institution: "VISA",
        tag: "coffee",
    },
    {
        id: "50",
        userId: "0",
        date: new Date("2025-11-12"),
        description: "Cineplex Popcorn/Soda",
        amount: 18.00,
        institution: "VISA",
        tag: "entertainment",
    },
    {
        id: "51",
        userId: "0",
        date: new Date("2025-11-13"),
        description: "Shell Gas Station",
        amount: 62.10,
        institution: "VISA",
        tag: "gas",
    },
    {
        id: "52",
        userId: "0",
        date: new Date("2025-11-14"),
        description: "Sushi Takeout",
        amount: 30.50,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "53",
        userId: "0",
        date: new Date("2025-11-15"),
        description: "Pet Food Store",
        amount: 49.99,
        institution: "VISA",
        tag: "pet_care",
    },
    {
        id: "54",
        userId: "0",
        date: new Date("2025-11-16"),
        description: "Farmers Market",
        amount: 28.00,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "55",
        userId: "0",
        date: new Date("2025-11-17"),
        description: "Bus Pass Purchase",
        amount: 90.00,
        institution: "Checking",
        tag: "transportation",
    },
    {
        id: "56",
        userId: "0",
        date: new Date("2025-11-18"),
        description: "Gym Membership Fee",
        amount: 45.00,
        institution: "Checking",
        tag: "health",
    },
    {
        id: "57",
        userId: "0",
        date: new Date("2025-11-19"),
        description: "Wendy's Lunch",
        amount: 14.80,
        institution: "VISA",
        tag: "restaurant",
    },
    {
        id: "58",
        userId: "0",
        date: new Date("2025-11-20"),
        description: "Walmart Grocery Pickup",
        amount: 88.63,
        institution: "VISA",
        tag: "groceries",
    },
    {
        id: "59",
        userId: "0",
        date: new Date("2025-11-21"),
        description: "Espresso Bar",
        amount: 5.50,
        institution: "VISA",
        tag: "coffee",
    },
    {
        id: "60",
        userId: "0",
        date: new Date("2025-11-22"),
        description: "Esso Gas Station",
        amount: 54.90,
        institution: "VISA",
        tag: "gas",
    },
    {
        id: "61",
        userId: "0",
        date: new Date("2025-11-23"),
        description: "Book Store Purchase",
        amount: 22.00,
        institution: "VISA",
        tag: "shopping",
    },
    {
        id: "62",
        userId: "0",
        date: new Date("2025-11-24"),
        description: "Hair Salon Visit",
        amount: 65.00,
        institution: "VISA",
        tag: "personal_care",
    },
    {
        id: "63",
        userId: "0",
        date: new Date("2025-11-25"),
        description: "Amazon Prime Video Rental",
        amount: 5.99,
        institution: "VISA",
        tag: "entertainment",
    },
    {
        id: "64",
        userId: "0",
        date: new Date("2025-11-26"),
        description: "Drug Store Medicine",
        amount: 14.75,
        institution: "VISA",
        tag: "health",
    },
    {
        id: "65",
        userId: "0",
        date: new Date("2025-11-27"),
        description: "The Beer Store",
        amount: 25.50,
        institution: "VISA",
        tag: "groceries", // Or "alcohol" if you use that tag
    },
    {
        id: "66",
        userId: "0",
        date: new Date("2025-11-28"),
        description: "Starbucks Treat",
        amount: 6.20,
        institution: "VISA",
        tag: "coffee",
    },
    {
        id: "67",
        userId: "0",
        date: new Date("2025-11-29"),
        description: "Home Hardware Light Bulbs",
        amount: 14.99,
        institution: "VISA",
        tag: "home_maintenance",
    },
    {
        id: "68",
        userId: "0",
        date: new Date("2025-11-30"),
        description: "Sunday Takeout - Indian",
        amount: 45.00,
        institution: "VISA",
        tag: "restaurant",
    },

    // --- Transactions 69-99 (Adding Variety and Volume) ---
    { id: "69", userId: "0", date: new Date("2025-11-01"), description: "Amazon.ca Batteries", amount: 12.99, institution: "VISA", tag: "shopping" },
    { id: "70", userId: "0", date: new Date("2025-11-02"), description: "Tim Hortons Drive Thru", amount: 9.25, institution: "VISA", tag: "coffee" },
    { id: "71", userId: "0", date: new Date("2025-11-03"), description: "Metro Groceries", amount: 55.40, institution: "VISA", tag: "groceries" },
    { id: "72", userId: "0", date: new Date("2025-11-04"), description: "Uber Ride", amount: 15.50, institution: "VISA", tag: "transportation" },
    { id: "73", userId: "0", date: new Date("2025-11-05"), description: "Shell Gas Station", amount: 61.80, institution: "VISA", tag: "gas" },
    { id: "74", userId: "0", date: new Date("2025-11-06"), description: "Dry Cleaning Service", amount: 25.00, institution: "VISA", tag: "personal_care" },
    { id: "75", userId: "0", date: new Date("2025-11-07"), description: "Pizza Slice Lunch", amount: 5.50, institution: "VISA", tag: "restaurant" },
    { id: "76", userId: "0", date: new Date("2025-11-08"), description: "Home Internet Upgrade Fee", amount: 20.00, institution: "Checking", tag: "utilities" },
    { id: "77", userId: "0", date: new Date("2025-11-09"), description: "Value Village Thrift", amount: 14.75, institution: "VISA", tag: "shopping" },
    { id: "78", userId: "0", date: new Date("2025-11-10"), description: "Bulk Coffee Beans", amount: 18.00, institution: "VISA", tag: "groceries" },
    { id: "79", userId: "0", date: new Date("2025-11-11"), description: "Amazon Prime Subscription (Annual)", amount: 119.00, institution: "VISA", tag: "subscription" },
    { id: "80", userId: "0", date: new Date("2025-11-12"), description: "Local Bakery", amount: 7.50, institution: "VISA", tag: "groceries" },
    { id: "81", userId: "0", date: new Date("2025-11-13"), description: "Cineplex Evening Show", amount: 14.00, institution: "VISA", tag: "entertainment" },
    { id: "82", userId: "0", date: new Date("2025-11-14"), description: "Esso Gas Station", amount: 57.65, institution: "VISA", tag: "gas" },
    { id: "83", userId: "0", date: new Date("2025-11-15"), description: "Doctor Co-pay Fee", amount: 35.00, institution: "Checking", tag: "health" },
    { id: "84", userId: "0", date: new Date("2025-11-16"), description: "Pho Restaurant Dinner", amount: 33.50, institution: "VISA", tag: "restaurant" },
    { id: "85", userId: "0", date: new Date("2025-11-17"), description: "Walmart Home Goods", amount: 45.00, institution: "VISA", tag: "shopping" },
    { id: "86", userId: "0", date: new Date("2025-11-18"), description: "Muffin and Coffee", amount: 5.75, institution: "VISA", tag: "coffee" },
    { id: "87", userId: "0", date: new Date("2025-11-19"), description: "LCBO Purchase", amount: 38.45, institution: "VISA", tag: "groceries" }, // Alcohol purchase
    { id: "88", userId: "0", date: new Date("2025-11-20"), description: "Car Battery Replacement", amount: 145.99, institution: "VISA", tag: "auto_maintenance" },
    { id: "89", userId: "0", date: new Date("2025-11-21"), description: "Netflix (Previous month refund)", amount: -16.99, institution: "VISA", tag: "subscription" }, // Example refund
    { id: "90", userId: "0", date: new Date("2025-11-22"), description: "Weekend Movie Rental", amount: 4.99, institution: "VISA", tag: "entertainment" },
    { id: "91", userId: "0", date: new Date("2025-11-23"), description: "A&W Lunch", amount: 12.00, institution: "VISA", tag: "restaurant" },
    { id: "92", userId: "0", date: new Date("2025-11-24"), description: "Loblaws Groceries", amount: 71.30, institution: "VISA", tag: "groceries" },
    { id: "93", userId: "0", date: new Date("2025-11-25"), description: "Parking Ticket Payment", amount: 40.00, institution: "Checking", tag: "transportation" },
    { id: "94", userId: "0", date: new Date("2025-11-26"), description: "Gym Personal Training Session", amount: 60.00, institution: "VISA", tag: "health" },
    { id: "95", userId: "0", date: new Date("2025-11-27"), description: "Gas Station Snack", amount: 3.50, institution: "VISA", tag: "groceries" },
    { id: "96", userId: "0", date: new Date("2025-11-28"), description: "Black Friday Clothing Haul", amount: 180.00, institution: "VISA", tag: "shopping" },
    { id: "97", userId: "0", date: new Date("2025-11-29"), description: "Shawarma Palace (Take 2)", amount: 13.50, institution: "VISA", tag: "restaurant" },
    { id: "98", userId: "0", date: new Date("2025-11-30"), description: "End of Month Savings Transfer", amount: -500.00, institution: "Checking", tag: "savings" }, // Example transfer
    { id: "99", userId: "0", date: new Date("2025-11-30"), description: "Water Bill Payment", amount: 35.80, institution: "Checking", tag: "utilities" },
    { id: "100", userId: "0", date: new Date("2025-11-30"), description: "Shell Gas Station", amount: 58.00, institution: "VISA", tag: "gas" },
];